### ISSUE TITLE
Correctly setup repr and str on the devices

### ISSUE THREAD

**Issue by apra93** [slaclab/HXRSnD#35]
## Expected Behavior

Scientists want to be able to get all the relevant info they need of a device by simply typing in the device name. However, this should not cause the logging.

## Current Behavior

Whenever a device is referred to in the logs, the device summary is printed, totally botching the log.

## Possible Solution

Explore the differences between `__repr__` and `__str__` and correctly configure the two.

## Steps to Reproduce (for bugs)

1. Take a look at the log file and it will be clear.

**Comment by ZLLentz** [comment]
I have a feeling ipython was never intended to be used this way, but a starting point:
https://stackoverflow.com/questions/1436703/difference-between-str-and-repr-in-python

If there is a conflict between the logfiles and the ipython user space that can't be resolved by adjusting `__str__` and `__repr__`, I suggest you just carefully pick out the `.name` attributes for the logging statements.

**Comment by apra93** [comment]
Punted on this by removing the ``repr`` method altogether for the aerotech and attocube motors in #47
